# Generated by Django 4.1.7 on 2023-02-23 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('vin_id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4, null=True)),
                ('make', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('detail_type', models.PositiveSmallIntegerField(choices=[(0, 'type1'), (1, 'type2')], default=0)),
                ('color', models.CharField(max_length=255, null=True)),
                ('dimensions', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.CreateModel(
            name='WeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_type', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='main.detailmodel')),
            ],
            options={
                'verbose_name': 'Weight',
                'verbose_name_plural': 'Weights',
            },
        ),
    ]
